CREATE TABLE IF NOT EXISTS USERS (
  nickname VARCHAR(255) NOT NULL PRIMARY KEY,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SHORTED_URL (
  id SERIAL PRIMARY KEY,
  original_url VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expirationTime BIGINT,
  accessCount INTEGER NOT NULL DEFAULT 0,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (user_id) REFERENCES USERS(nickname)
);

CREATE TABLE IF NOT EXISTS USER_URL (
  user_id VARCHAR(255) NOT NULL,
  url_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS(nickname),
  FOREIGN KEY (url_id) REFERENCES SHORTED_URL(id),
  PRIMARY KEY (user_id, url_id)
);